routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {

	Route::resource('alumnos', 'AlumnoController');

	Route::put('alumnos','AlumnoController@changeFingreso')->name('alumnos.changeFingreso');

	Route::resource('personas', 'PersonaController', ['except' => 'index']);

	Route::get('personas/tipo/{tipo}','PersonaController@index')->name('personas.index');
	

});

app/Alumno.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alumno extends Model
{

    protected $table='alumnos';
	protected $primaryKey = 'id';

	protected $fillable = array(
        		'cedula','nombres','apellidos','sexo',
				'f_nacimiento','email','estatus','telefono',
				'estado_civil','direccion','estado','estudia',
				'l_estudia','nivel'
    );

    protected $hidden = ['created_at','update_at'];

    public function persona()
    {
    	return $this->hasMany(Persona::class);
    }
}

app/Persona.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Persona extends Model
{
	protected $table='personas';

    public function alumno()
    {
    	return $this->hasMany(Alumno::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AlumnoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\AlumnoRequest;
use App\Http\Requests;
use App\Alumno;
use Auth;

class AlumnoController extends Controller
{

	protected $fields = [
		'expediente' => '',
		'nombres' => '',
		'apellidos' => '',
		'sexo' => '',
		'cedula' => '',
		'foto' => 'no_foto.png',
		'f_nacimiento' => '',
		'email' => '',
		'estatus' => '',
		'estado_civil' => '',
		'f_ingreso' => '',
		'direccion' => '',
		'estado' => 'A',
		'telefono' => '',
		'estudia' => '',
		'l_estudia' => '',
		'nivel' => '',
		'user_id' => '',
	];

	public function index(Request $request)
	{
		$alumnos = Alumno::where('nombres','like','%'.$request->input('buscar').'%')
			->orWhere('apellidos','like','%'.$request->input('buscar').'%')
			->orderBy('id', 'desc')->paginate(config('application.elem_por_pag'));
		
		return view('alumnos.index')->with('alumnos',$alumnos);
	}

	public function show($id)
	{
		$alumno = Alumno::findOrFail($id);
		return view('alumnos.show')->with('alumno',$alumno);
	}

    public function create()
    {
    	return view('alumnos.create');
    }


	public function store(AlumnoRequest $request)
	{

		$alumno = new Alumno();
		$alumno->expediente = getNroExpediente('alumnos');
		$alumno->cedula = $request->input('cedula');
		$alumno->nombres = $request->input('nombres');
		$alumno->apellidos = $request->input('apellidos');
		$alumno->sexo = $request->input('sexo');
		$alumno->f_nacimiento = $request->input('f_nacimiento');
		$alumno->email = $request->input('email');
		$alumno->estatus = $request->input('estatus');
		$alumno->telefono = $request->input('telefono');
		$alumno->estado_civil = $request->input('estado_civil');
		$alumno->direccion = $request->input('direccion');
		$alumno->estado = $request->input('estado');
		$alumno->estudia = $request->input('estudia');
		$alumno->l_estudia = $request->input('l_estudia');
		$alumno->nivel = $request->input('nivel');
		$alumno->user_id = Auth::user()->id;
		$alumno->f_ingreso = date('Y-m-d');

    	$alumno->save();

    	//return view('alumnos.show')->with(['alumno'=>$alumno,'success-message'=>'Alumno '.getFullNombre('alumnos',$alumno->id).' insertado correctamente!.']);
    	//return redirect()->to('/alumnos')->with('success-message','Alumno'.getFullNombre($alumno->id).' insertado correctamente!.');
		return redirect()->route('alumnos.show',$alumno->id)->with('success-message','Alumno ' . getFullNombre('alumnos',$alumno->id).'
			insertado correctamente.');

	}

	public function edit($id)
	{
		$alumno = Alumno::findOrFail($id);

		return view('alumnos.edit',['alumno'=>$alumno]);
	}

	public function update(Request $request, $id)
	{
		$this->validate($request, [
           	'nombres' => 'required|string|min:3',
            'apellidos' => 'required|string|min:3',
            'f_nacimiento' => 'required',
            'email'=>'required|email|unique:alumnos,email,'.$id,
            'sexo' => 'required',
            'direccion' => 'required',

        ]);

		$alumno = Alumno::findOrFail($id);

		$input = $request->only(['cedula','nombres','apellidos','sexo',
								'f_nacimiento','email','estatus','telefono',
								'estado_civil','direccion','estado','estudia',
								'l_estudia','nivel']);

		$alumno->fill($input)->save();

		return redirect()->route('alumnos.edit', $id)->with('success-message','Datos del Alumno '. getFullNombre('alumnos',$alumno->id) .' actualizados!.');		
	}

	public function changeFingreso(Request $request)
	{
		$alumno = Alumno::find($request->id);
		$alumno->f_ingreso = ($request->f_ingreso);
		$alumno->save();

		return redirect()->route('alumnos.show',$alumno->id)->with('success-message','Actualizada fecha de ingreso!.');
	}


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PersonaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Persona;

class PersonaController extends Controller
{
    public function index($tipo)
    {

    	switch ($tipo) {
    		case 'profesores':
    			$tipersona = 1;
    			break;
    		case 'representantes':
    			$tipersona = 0;
    			break;
    	}

    	$personas = Persona::where('isprofesor', $tipersona)
    			->orderBy('id', 'desc')
    			->paginate(config('application.elem_por_pag'));

    	return view('personas.index',['personas'=>$personas,'tipo'=>$tipo,]);
    }

    public function create()
    {
    	return view('personas.create');
    }
}

resources/views/alumnos/create.blade.php
@extends('layouts.app')

@section('titulo')
{{ config('application.nombre')}} | Agregar Alumno
@endsection

@section('content')
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="panel-title">
				<i class="fa fa-user-plus"></i> Agregar Alumno
			</div>
		</div>
		<div class="panel-body">
			@include('layouts.partials.error')
			<form action="{{ route('alumnos.store') }}" method="POST" class="form-horizontal">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">

				<div class="form-group{{ $errors->has('cedula') ? ' has-error' : '' }} has-feedback">
					<label for="cedula" class="col-md-3 control-label">
						Cédula
					</label>	
						<div class="col-md-3">
							<input type="text" class="form-control" name="cedula" id="cedula" pattern="^([VEJPG]{1})([0-9]{7,9})$" value="{{ old('cedula') }}" placeholder="Ejemplo V12345778" >
						</div>
				</div>
				<div class="form-group">
					<label for="nombres" class="col-md-3 control-label">
						Nombres
					</label>	
						<div class="col-md-8">
							<input type="text" class="form-control" name="nombres" id="nombres" value="{{ old('nombres') }}" required>
						</div>
				</div>
				<div class="form-group">
					<label for="apellidos" class="col-md-3 control-label">
						Apellidos
					</label>	
						<div class="col-md-8">
							<input type="text" class="form-control" name="apellidos" id="nombre" value="{{ old('apellidos') }}" required>
						</div>
				</div>

				<div class="form-group">
					<label for="reverse_direction" class="col-md-3 control-label">
						Sexo
					</label>	
						<div class="col-md-4">
							<label class="radio-inline">
								<input type="radio" name="sexo" id="sexo" 
								@if (old('sexo')=='M')
									checked="checked"
								@endif
								value="M"> Masculino	
							</label>
							<label class="radio-inline">
								<input type="radio" name="sexo" 
								@if (old('sexo') == 'F')
									checked="checked"
								@endif
								value="F"> Femenino	
							</label>
							<label class="radio-inline">
								<input type="radio" name="sexo" 
								@if (old('sexo') == 'O')
									checked="checked"
								@endif
								value="O"> Otro	
							</label>	
						</div>
					<label for="estatus" class="col-md-1 control-label">
						Estatus
					</label>	
						<div class="col-md-2">
							<select name="estatus" class="form-control">
								@foreach( estatusAlumno() as $estatus => $status)
									<option  value="{{ $estatus }}">{{ $status }}</option>
								@endforeach
							</select>
						</div>

				</div>
				<div class="form-group">
					<label for="email" class="col-md-3 control-label">
						Correo Electrónico
					</label>	
						<div class="col-md-3">
							<input type="email" class="form-control" name="email" id="email" value="{{ old('email') }}" required placeholder="prueba@ejemplo.com">
						</div>

					<label for="telefono" class="col-md-2 control-label">
						Telefóno
					</label>	
					<div class="col-md-3">
						<div class="input-group">
							<div class="input-group-addon">
                    			<i class="fa fa-phone"></i>
                  			</div>
							<input type="tel"  pattern="[0-9]{4}-?[0-9]{7}" class="form-control" name="telefono" id="telefono" data-inputmask='"mask": "9999-9999999"' data-mask value="{{ old('telefono') }}" placeholder="0416-1234567">
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="f_nacimiento" class="col-md-3 control-label">
						Fecha de Nacimiento
					</label>	
						<div class="col-md-2">
							<div class="input-group">
								<span class="input-group-addon">
									<span class="fa fa-calendar"></span>
								</span>
									<input class="form-control input-sm" type="date" name="f_nacimiento" id="f_nacimiento" value="{{ old('f_nacimiento') }}" max="<?php echo date('Y-m-d'); ?>" step="1" required autocomplete="on" >
							</div>
						</div>

					<label for="estado_civil" class="col-md-2 control-label">
						Estado Civil
					</label>	
						<div class="col-md-3">
							<select name="estado_civil" class="form-control">
								@foreach( estadoCivil() as $estado => $stat)
									<option  value="{{ $estado }}">{{ $stat }}</option>
								@endforeach
							</select>
						</div>
				</div>
				<div class="form-group">
					<label for="direccion" class="col-md-3 control-label">
						Dirección
					</label>	
						<div class="col-md-4">
							<textarea class="form-control" name="direccion" id="direccion" rows="2">{{ old('direccion') }}
							</textarea>
						</div>
					<label for="estado" class="col-md-1 control-label">
						Estado
					</label>	
						<div class="col-md-3">
							<select name="estado" class="form-control">
								@foreach( estadoPais() as $estado => $stado)
									<option  value="{{ $estado }}">{{ $stado }}</option>
								@endforeach
							</select>
						</div>

				</div>
				<hr>
				<div class="form-group">
					<label for="reverse_direction" class="col-md-3 control-label">
						Estudia?
					</label>	
						<div class="col-md-2">
							<label class="radio-inline">
								<input type="radio" name="estudia" id="estudia" 
								@if ( old('estudia') )
									checked="checked"
								@endif
								value="1"> Si	
							</label>
							<label class="radio-inline">
								<input type="radio" name="estudia" id="estudia" 
								@if ( ! old('estudia') )
									checked="checked"
								@endif
								value="0"> No	
							</label>	
						</div>
					<label for="reverse_direction" class="col-md-3 control-label">
						Nivel
					</label>
					<div class="col-md-3">
						<input type="text" class="form-control" name="nivel" id="nivel" value="{{ old('nivel') }}" placeholder="Ejemplo 6to Grado">
					</div>

				</div>
				<div class="form-group">
					<label for="direccion" class="col-md-3 control-label">
						Instituto Estudia
					</label>	
						<div class="col-md-8">
							<input type="text" class="form-control" name="l_estudia" id="l_estudia" value="{{ old('l_estudia') }}" placeholder="Ejemplo Liceo de Ejido">
						</div>
				</div>


				<div class="form-group">
					<div class="col-md-7 col-md-offset-3">
						<button type="submit" class="btn btn-success btn-md"><i class="fa fa-plus"></i>&nbsp; Agregar</button>
						<a href="{{ route('alumnos.index') }}" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Volver</a>
					</div>
				</div>
			
			</form>
		</div>
	</div>

@endsection

resources/views/alumnos/edit.blade.php
@extends('layouts.app')

@section('titulo')
{{ config('application.nombre')}} | Editar Alumno {{ $alumno->id}}
@endsection

@section('content')
<div class="panel panel-default">
		<div class="panel-heading">
			<div class="panel-title">
				<i class="fa fa-edit"></i> Editar Alumno
			</div>
		</div>
		<div class="panel-body">
			@include('layouts.partials.error')
			@include('layouts.partials.message')
			
			<form action="{{ route('alumnos.update', $alumno->id) }}" method="POST" class="form-horizontal">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">
				<input type="hidden" name="_method" value="PUT">
				
				<div class="form-group">
					<label for="expediente" class="col-md-3 control-label">
						Expediente
					</label>	
						<div class="col-md-2">
							<input type="text" class="form-control" name="expediente" id="expediente" pattern="^([VEJPG]{1})([0-9]{7,9})$" value="{{ $alumno->expediente }}" placeholder="V12345678" readonly>
						</div>


					<label for="cedula" class="col-md-3 control-label">
						Cédula
					</label>	
						<div class="col-md-3">
							<input type="text" class="form-control" name="cedula" id="cedula" value="{{ $alumno->cedula }}" placeholder="Ejemplo V12345778">
						</div>
				</div>
				<div class="form-group">
					<label for="nombres" class="col-md-3 control-label">
						Nombres
					</label>	
						<div class="col-md-8">
							<input type="text" class="form-control" name="nombres" id="nombres" value="{{ $alumno->nombres }}" required>
						</div>
				</div>
				<div class="form-group">
					<label for="apellidos" class="col-md-3 control-label">
						Apellidos
					</label>	
						<div class="col-md-8">
							<input type="text" class="form-control" name="apellidos" id="nombre" value="{{ $alumno->apellidos }}" required>
						</div>
				</div>

				<div class="form-group">
					<label for="reverse_direction" class="col-md-3 control-label">
						Sexo
					</label>	
						<div class="col-md-4">
							<label class="radio-inline">
								<input type="radio" name="sexo" id="sexo" 
								@if ($alumno->sexo=='M')
									checked="checked"
								@endif
								value="M"> Masculino	
							</label>
							<label class="radio-inline">
								<input type="radio" name="sexo" 
								@if ($alumno->sexo == 'F')
									checked="checked"
								@endif
								value="F"> Femenino	
							</label>
							<label class="radio-inline">
								<input type="radio" name="sexo" 
								@if ($alumno->sexo == 'O')
									checked="checked"
								@endif
								value="O"> Otro	
							</label>	
						</div>
					<label for="estatus" class="col-md-1 control-label">
						Estatus
					</label>	
						<div class="col-md-2">
							<select name="estatus" class="form-control">
								<option value="{{ $alumno->estatus }}">{{ getEstatusAlumno($alumno->estatus) }}</option>
								@foreach( estatusAlumno() as $estatus => $status)
									<option  value="{{ $estatus }}">{{ $status }}</option>
								@endforeach
							</select>
						</div>

				</div>
				<div class="form-group">
					<label for="email" class="col-md-3 control-label">
						Correo Electrónico
					</label>	
						<div class="col-md-3">
							<input type="email" class="form-control" name="email" id="email" value="{{ $alumno->email }}" required placeholder="prueba@ejemplo.com">
						</div>
					<label for="telefono" class="col-md-2 control-label">
						Telefóno
					</label>	
					<div class="col-md-3">
						<div class="input-group">
							<div class="input-group-addon">
                    			<i class="fa fa-phone"></i>
                  			</div>
							<input type="tel"  pattern="[0-9]{4}-?[0-9]{7}" class="form-control" name="telefono" id="telefono" data-inputmask='"mask": "9999-9999999"' data-mask value="{{ $alumno->telefono }}" placeholder="0416-1234567">
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="email" class="col-md-3 control-label">
						Fecha de Nacimiento
					</label>	
						<div class="col-md-2">
							<div class="input-group">
								<span class="input-group-addon">
									<span class="fa fa-calendar"></span>
								</span>
									<input class="form-control input-sm" type="date" name="f_nacimiento" id="f_nacimiento" value="{{ getFormatDate($alumno->f_nacimiento) }}" max="<?php echo date('Y-m-d'); ?>" step="1" required autocomplete="on" >
							</div>
						</div>

					<label for="estado_civil" class="col-md-3 control-label">
						Estado Civil
					</label>	
						<div class="col-md-3">
							<select name="estado_civil" class="form-control">
									<option value="{{ $alumno->estado_civil }}">{{ getEstadoCivil($alumno->estado_civil) }}</option>
								@foreach( estadoCivil() as $estado => $stat)
									<option  value="{{ $estado }}">{{ $stat }}</option>
								@endforeach
							</select>
						</div>
				</div>
				<div class="form-group">
					<label for="direccion" class="col-md-3 control-label">
						Dirección
					</label>	
						<div class="col-md-4">
							<textarea class="form-control" name="direccion" id="direccion" rows="2">{{ $alumno->direccion }}
							</textarea>
						</div>
					<label for="estado" class="col-md-1 control-label">
						Estado
					</label>	
						<div class="col-md-3">
							<select name="estado" class="form-control">
								<option value="{{ $alumno->estado }}">{{ getEstadoPais($alumno->estado) }}</option>
								@foreach( estadoPais() as $estado => $stado)
									<option  value="{{ $estado }}">{{ $stado }}</option>
								@endforeach
							</select>
						</div>

				</div>
				<hr>
				<div class="form-group">
					<label for="reverse_direction" class="col-md-3 control-label">
						Estudia?
					</label>	
						<div class="col-md-2">
							<label class="radio-inline">
								<input type="radio" name="estudia" id="estudia" 
								@if ( $alumno->estudia )
									checked="checked"
								@endif
								value="1"> Si	
							</label>
							<label class="radio-inline">
								<input type="radio" name="estudia" id="estudia" 
								@if ( ! $alumno->estudia )
									checked="checked"
								@endif
								value="0"> No	
							</label>	
						</div>
					<label for="reverse_direction" class="col-md-3 control-label">
						Nivel
					</label>
					<div class="col-md-3">
						<input type="text" class="form-control" name="nivel" id="nivel" value="{{ $alumno->nivel }}" placeholder="Ejemplo 6to Grado">
					</div>

				</div>
				<div class="form-group">
					<label for="direccion" class="col-md-3 control-label">
						Instituto Estudia
					</label>	
						<div class="col-md-8">
							<input type="text" class="form-control" name="l_estudia" id="l_estudia" value="{{ $alumno->l_estudia }}" placeholder="Ejemplo Liceo de Ejido">
						</div>
				</div>


				<div class="form-group">
					<div class="col-md-7 col-md-offset-3">
						<button type="submit" class="btn btn-success btn-md"><i class="fa fa-save"></i>&nbsp; Guardar</button>
						<a href="{{ route('alumnos.show',$alumno->id) }}" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Volver</a>
					</div>
				</div>
			
			</form>
		</div>
	</div>
@endsection

@section('scripts')
<script type="text/javascript">
	$(document).ready(function(){
		var estatus = $("input[name='estatus']").val();
		var estado_civil = $("input[name='estado_civil']").val();
		var estado = $("input[name='estado']").val();
		
	

		alert(estatusAlumno());
	});
</script>
@endsection

resources/views/alumnos/index.blade.php
@extends('layouts.app')

@section('titulo')
{{ config('application.nombre')}} | Alumnos
@endsection

@section('content')

<div class="panel panel-default">
	<div class="panel-heading">
		<h1 class="text-primary text-right">
			<i class="fa fa-users"></i> Alumnos
			<a href="{{ route('alumnos.create') }}" class="btn btn-success btn-sm pull-left"><i class="fa fa-plus"></i> Nuevo Alumno</a>
		</h1>
	</div>
	<div class="panel-body">
		@include('layouts.partials.error')
		@include('layouts.partials.message')

		@if ($alumnos->count())
			<div class="search">
				<form action="{{ route('alumnos.index')}}" method="GET" class="form-horizontal">
					<div class="form-group">
						<div class="input-group col-sm-offset-1 col-sm-10">
							<input type="text" name="buscar" class="form-control" value="{{ request()->buscar }}" placeholder="Buscar Alumnos..">
							<span class="input-group-btn">
								<button type="submit" class="btn btn-default"><i class="fa fa-btn fa-search"></i> Buscar</button>
							</span>
						</div>
					</div>
				</form>
			</div>
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th># Expediente</th>
						<th>Cédula</th>
						<th>Nombres</th>
						<th>Apellidos</th>
						<th>Estatus</th>
					</tr>
				</thead>	
				<tbody>
					@foreach ($alumnos as $alumno)
					<tr class="">
						<td><a href="{{ route('alumnos.show',$alumno->id)}}">{{ $alumno->expediente }}</td></a>
						<td>{{ $alumno->cedula }}</td>
						<td>{{ $alumno->nombres }}</td>
						<td>{{ $alumno->apellidos }}</td>
						<td><span class="badge">{{ getEstatus($alumno->estatus) }}</span></td>
					</tr>
					@endforeach
				</tbody>
			</table>
			<div class="text-center">
				{{ $alumnos->links() }}
			</div>
		@else
			<h3>No hay Alumnos</h3>
		@endif

	</div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
		
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/partials/error.blade.php
@if (count($errors) > 0 )
	<div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert">x</button>
			<strong>Whooops! Algo está mal!!!!</strong>
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
	</div>
@endif

resources/views/layouts/partials/footer.blade.php
        <strong>Copyright &copy; <?php echo date('Y').' '; ?> <a href="http://www.sercontec.com.ve" title="Servicio y Consultoría Tecnológica GUMA">Ing. German Gutierrez</a>.</strong> Todos los derechos reservados.

resources/views/layouts/partials/message.blade.php
@if (Session::has("success-message"))
	<div class="alert alert-success alert-block">
	        <button type="button" class="close" data-dismiss="alert">&times;</button>
	            <strong>{{ Session::get("success-message") }}</strong>
    </div>
@elseif (Session::has("error-message"))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>{{ Session::get("error-message") }}</strong>
    </div>
@endif

resources/views/personas/create.blade.php
@extends('layouts.app')
@section('titulo')
{{ config('application.nombre')}} |
@endsection

resources/views/personas/index.blade.php
@extends('layouts.app')

@section('titulo')
{{ config('application.nombre')}} | {{ ucfirst($tipo) }}
@endsection

@section('content')
<div class="panel panel-default">
	<div class="panel-heading">
		<h1 class="text-primary text-right">
			<i class="fa fa-users"></i> {{ ucfirst($tipo) }} 
			<a href="{{ route('personas.create','tipo', $tipo) }}" class="btn btn-success btn-sm pull-left"><i class="fa fa-plus"></i> Nuevo {{ ucfirst($tipo) }}</a>
		</h1>
	</div>
	<div class="panel-body">
		@if ($personas)
		
		<div class="">
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Cédula</th>
						<th>Nombres</th>
						<th>Apellidos</th>
						<th>Condición</th>
					</tr>
				</thead>
				<tbody>
					@foreach($personas as $persona)
					<tr>
						<td><a href="{{ route('personas.show',['persona'=>$persona->id,'tipo'=>$tipo])}}">{{ $persona->cedula }}</a></td>
						<td>{{ $persona->nombres }}</td>
						<td>{{ $persona->apellidos }}</td>
						<td><span class="badge">{{ getEstatus($persona->estatus) }}</span></td>
					</tr>
					@endforeach
				</tbody>
			</table>
			<div class="text-center">
				{!! $personas->links() !!} 	
			</div>
		</div>

		 
		@else 
			No hay registrado {{ ucfirst($tipo)}}
		@endif

	</div>
</div>
@endsection